default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tennis_rails_development

test:
  <<: *default
  database: tennis_rails_test

production:
  <<: *default
  database: tennis_rails_production
  username: <%= ENV['TENNIS_DATABASE_USERNAME'] %>
  password: <%= ENV['TENNIS_DATABASE_PASSWORD'] %>
